### ISSUE TITLE
Tópicos Extras

### ISSUE THREAD

**Issue by AnaJordao** [CPeluti/fso-trabalho#11]
Gerenciador de pacotes

**Comment by CPeluti** [comment]
# Gerenciador de pacotes

O Debian possui varios softwares que são usados para gerenciar os debian packages.

Dentre eles temos alguns que são amplamente utilizados:
- dpkg
- APT
- aptitude
- synaptic

Dentre eles, os de alto nível dependem de outros gerenciadores, como por exemplo o aptitude depende do apt, que por sua vez depende do dpkg.

O dpkg é o principal software de gerenciamento de pacotes.
É ele que cuida das instalações do pacotes de maneira local

O APT é o gerenciador de pacotes que dispõe o apt-get. Ele provê uma interface por linha de comando para pesquisar e gerenciar os pacotes através de seus repositórios.

Por padrão o Debian possui seus repósitorios no arquivo que está no caminho /etc/apt/sources.list

Exemplo de arquivo:
```
deb http://deb.debian.org/debian bullseye main
deb-src http://deb.debian.org/debian bullseye main

deb http://deb.debian.org/debian-security/ bullseye-security main
deb-src http://deb.debian.org/debian-security/ bullseye-security main

deb http://deb.debian.org/debian bullseye-updates main
deb-src http://deb.debian.org/debian bullseye-updates main
```

# Fontes
[Manual do debian](https://www.debian.org/doc/manuals/debian-faq/pkgtools.en.html)
[Wiki do debian](https://wiki.debian.org/SourcesList)

**Comment by CPeluti** [comment]
# Ambientes gráficos
O debian possui como padrão o Gnome, porém é possível utilizar outros Desktop Enviroments (DE) como o XFCE e o KDE.
![Image](https://user-images.githubusercontent.com/37275856/214444805-5bc2b18d-423d-48aa-b273-0cbb57a70084.png)

Geralmente distros de servidores são mínimas e não costumam ter um ambiente gráfico por padrão.


Outras alternativas aos DE's são os Window Managers (WM) como o I3 e o xMonad.

![Image](https://user-images.githubusercontent.com/37275856/214444883-77963d37-9735-446d-a41c-f2c1fd9aa5bd.png)
