### ISSUE TITLE
Gerencia de Processos

### ISSUE THREAD

**Issue by AnaJordao** [CPeluti/fso-trabalho#4]

**Comment by ngsylar** [comment]
O Debian é um sistema multiprocessamento e utiliza multiprogramação. Assim, possui a capacidade de trabalhar com mais de um processador, cada um ocupado com um processo e evita que o sistema fique travado caso um processo falhe.

O sistema usa o vetor _task_, que é uma matriz de ponteiros de _task_struct_, que representam os processos que existem na memória. A quantidade máxima de processos é limitada por essse vetor.

**Comment by ngsylar** [comment]
_task_struct_, de maneira mais geral, contém os seguintes campos:
- estado do processo,
- informações de escalonamento (ex: prioridade),
- identificadores (PID, UID, GID),
- ponteiros (para processos pais, irmãos e filhos - pois os processos são criados por meio de cópias que um dado processo pai cria, criando essa relação de dependência entre processos),
- temporizadores,
- sistema de arquivos (com ponteiros para descritores de arquivos abertos para o processo e v-nodes para o diretório onde o processo se encontra e para o diretório onde ele está trabalhando - evita por exemplo tentativas de deleção enquanto um processo ou arquivo está aberto),
- espaço de endereçamento de memória virtual (que deve ser mapeada para a memória física pelo kernel)
- contexto de hardware (registradores)

**Comment by ngsylar** [comment]
O algoritmo de escalonamento de tarefas usado é o CFS (**Completely Fair Scheduler**), que se baseia em múltiplas filas de execução, uma para cada núcleo de processamento. Entretanto, cada fila não consiste em estruturas reais de filas, mas em árvores rubro-negras que fornecem a ordem de execução de tarefas baseada nos pesos e cargas de cada.

O peso basicamente representa os campos que descrevem a prioridade do processo e a carga é um cálculo baseado no tempo médio de execução da tarefa. Esse tempo é medido virtualmente, ou seja, representa o tempo total de execução do processo sempre que ele tem posse do processador até o momento atual.

O CFS mata a noção clássica de quantum, fazendo com que as fatias de tempo sejam distintas e variáveis a cada troca de contexto. A árvore rubro-negra é um tipo especial de árvore binária de busca que é auto-balanceável. Cada nó representa uma tarefa e o valor guardado em nó representa o tempo de execução virtual, com o menor estando sempre mais a esquerda da árvore.

Quando a fatia de tempo para uma tarefa em execução acaba, o tempo de execução virtual dela é incrementado e ela é inserida novamente na árvore. O próximo processo a ganhar o processador será o nó mais a esquerda da árvore, que possui o menor tempo de execução até então. Assim, a distribuição de tempo de processamento fica justa para todas as tarefas que estão em espera e o fenômeno de _starvation_ é evitado, pois todas estarão do lado mais esquerdo em algum momento.

O custo de inserção/remoção de um nó da árvore é O(log n).

Quando o distribuição de carga entre os núcleos fica desbalanceada, procura-se o núcleo mais ocioso e executa nele um processo de balanceamento das filas. Assim as filas são balanceadas, nenhum núcleo fica mais sobrecarregado que outro e nenhum fica ocioso. Essa operação entretanto é bastante custosa e, portanto, feita apenas quando um núcleo se sente sobrecarregado.

**Comment by ngsylar** [comment]
**Fontes:**
- [The Linux Kernel: Table of Contents](https://tldp.org/LDP/tlk/tlk-toc.html)
- [CFS group scheduling](https://lwn.net/Articles/240474/)
- [The Linux Scheduler: a Decade of Wasted Cores](https://blog.acolyer.org/2016/04/26/the-linux-scheduler-a-decade-of-wasted-cores/)
- [Red-Black Trees](https://pages.cs.wisc.edu/~paton/readings/Red-Black-Trees/)

**Comment by ngsylar** [comment]
IPC (Interprocess Communication)

O Debian tem suporte a comunicação entre processos através de memória compartilhada e troca de mensagens.

### Sinais:
Sinais são mensagens assíncronas enviadas entre processos. Cada processo escolhe como irá lidar com os sinais recebidos, podendo inclusive ignorá-los ou ceder a manipulação ao kernel. Existem sinais especiais que não podem ser ignorados, eles serão tratadas pelo kernel.

Nem todos os processos podem enviar sinais, isso depende do UID e do GID, pois usuários e grupos de processos possuem permissões próprias.

### Pipes:
Pipes são redirecionamentos em que a saída de um comando serve de entrada para outro. No Debian, dois processos distintos podem se comunicar através de um pipe, referenciando um v-node que aponta para uma página de dados que será descartada ao final da comunicação. Os pipes oferecem uma abstração para as chamadas de sistema para gravação e leitura padrões. O kernel sincroniza o acesso aos dados do pipe através de filas de espera, bloqueios e sinais.

### Memória compartilhada:
Processos distintos podem adquirir o acesso a um espaço de memória que será compartilhado entre eles. O acesso a essa área é permitido apenas pelos processos que receberam o direito ao acesso ou por meio de chaves. Uma vez que uma área da memória está sendo compartilhada, é responsabilidade dos processos a forma de manipular os dados internos a ela. Para isso, podem ser usados semáforos ou outros mecanismos de bloqueio.
