### ISSUE TITLE
Gerência de Arquivos

### ISSUE THREAD

**Issue by AnaJordao** [CPeluti/fso-trabalho#5]

**Comment by CPeluti** [comment]
O Debian utiliza como padrão o ext4.
Ele possui um monte de outros filesystems diponiveis ( [wiki do debian](https://wiki.debian.org/FileSystem#:~:text=In%20Debian%2C%20ext4%20is%20the,system%20crashes%20or%20power%20failures.)

Os mais notaveis são fat, ntfs, nfs, ext4 e zfs.

Em sistemas Gnu/linux os conteudos de um filesystem podem ser montados em um diretorio (usando o comando de mount ou editando o fstab).
Por exemplo, você pode montar o device /dev/sda2 no /home/usuario tornando possível acessar o sda2 no diretório usuario dentro do diretório home, isso é especialmente util para separar em multiplas partições o armazenamento do root e da home.
