### ISSUE TITLE
Tipo de Kernel

### ISSUE THREAD

**Issue by AnaJordao** [CPeluti/fso-trabalho#8]

**Comment by CPeluti** [comment]
# Kernel que o debian usa

Apesar do debian utilizar o Linux kernel como principal e padrão, é possível utilizar outros kernels como:

- [Hurd](https://wiki.debian.org/TheHurd) (microkernel)

- [kFreeBSD](https://wiki.debian.org/Debian_GNU/kFreeBSD)

- [NetBSD](https://www.debian.org/ports/netbsd/)

# Tipo de kernel

O Linux e modular é monolítico e modular.
O kernel ser modular é especialmente importante para que cada distro possa ter o kernel atendendo suas necessidades.
Isso fica bem evidente na distro Gentoo, a qual é comum o próprio usuário compilar seu kernel.

# Versionamento 
Existem varias categoria que um release do kernel pode entrar, sendo elas:
- Prepatch
Precisa ser compilado a partir do source, tem como alvo kernel devs e entusiastas do linux
- Mainline
Mantida pelo Torvalds, têm releases a cada 9-10 semanas, é onde todas as features novas são introduzidas.
- Stable
É utilizado para bugfix que são portadas de volta para a mainline
- Longterm(LTS)
Existem varios releases de kernel de longterm com o objetivo de levar bugfixes para kenels mais antigos. Apenas bugfixes importantes são aplicados para esses kernels.

##  Longterm release kernels

Version | Maintainer | Released | Projected EOL
-- | -- | -- | --
5.15 | Greg Kroah-Hartman & Sasha Levin | 2021-10-31 | Oct, 2023
5.10 | Greg Kroah-Hartman & Sasha Levin | 2020-12-13 | Dec, 2026
5.4 | Greg Kroah-Hartman & Sasha Levin | 2019-11-24 | Dec, 2025
4.19 | Greg Kroah-Hartman & Sasha Levin | 2018-10-22 | Dec, 2024
4.14 | Greg Kroah-Hartman & Sasha Levin | 2017-11-12 | Jan, 2024

<br class="Apple-interchange-newline">
</body>
</html>

# Fontes
- [ArchWiki](https://wiki.archlinux.org/title/kernel)
- [Kernel Docs](https://docs.kernel.org/)
- [Kernel](https://www.kernel.org/category/releases.html)
- [Kernel Wikipedia](https://en.wikipedia.org/wiki/Linux_kernel)
